// src/components/SessionSidebar.vue
<script setup lang="ts">
import {
  Connection,
  Delete,
  Edit,
  FolderOpened,
  Plus,
  Search
} from "@element-plus/icons-vue";
import type { SavedSession } from "@/domain/session";

defineProps<{
  sessions: SavedSession[];
  activeId: string;
  openedCount: number;
}>();
const query = defineModel<string>("query", {
  required: true
});
defineEmits<{
  duplicate: [session: SavedSession];
  edit: [session: SavedSession];
  remove: [id: string];
  create: [];
}>();
</script>

<template>
  <aside class="sidebar">
    <div class="sidebar-head">
      <div>
        <span>会话</span
        ><small>{{ sessions.length }}</small>
      </div>
      <button
        class="icon-button primary"
        title="新建 SSH 会话"
        @click="$emit('create')"
      >
        <Plus />
      </button>
    </div>
    <label class="search-box">
      <Search />
      <input
        v-model="query"
        aria-label="搜索会话"
        placeholder="搜索会话"
    /></label>
    <div class="group-title">
      <span>我的会话</span>
      <FolderOpened />
    </div>
    <div class="session-list">
      <button
        v-for="session in sessions"
        :key="session.id"
        class="session-item"
        :class="{
          active: activeId === session.id
        }"
        @dblclick="$emit('duplicate', session)"
      >
        <span class="session-icon"
          ><Connection
        /></span>
        <span class="session-copy"
          ><strong>{{ session.name }}</strong
          ><small>{{
            session.kind === "local"
              ? "本机终端"
              : `${session.username ? session.username + "@" : ""}${session.host}:${session.port}`
          }}</small></span
        >
        <span
          v-if="session.id !== 'local'"
          class="edit"
          title="编辑"
          @click.stop="$emit('edit', session)"
          ><Edit
        /></span>
        <span
          v-if="session.id !== 'local'"
          class="delete"
          title="删除"
          @click.stop="
            $emit('remove', session.id)
          "
          ><Delete
        /></span>
      </button>
      <p
        v-if="!sessions.length"
        class="empty-list"
      >
        没有匹配的会话
      </p>
    </div>
    <div class="sidebar-foot">
      <span class="status-dot"></span
      ><span>就绪</span
      ><small>{{ openedCount }} 个连接</small>
    </div>
  </aside>
</template>

// src/sessions/components/SessionSidebar.tsx
import type { SavedSession } from "@/sessions/lib/session";
import {
  Button,
  Header,
  Input,
  ListBox,
  TextField
} from "@heroui/react";
import Hint from "@/shared/components/Hint";
import { useT } from "@/settings/lib/i18n";
import {
  PlusOutlined,
  SearchOutlined,
  FolderOpenOutlined,
  LinkOutlined,
  EditOutlined,
  DeleteOutlined
} from "@ant-design/icons";

type Props = {
  sessions: SavedSession[];
  activeId: string;
  openedCount: number;
  query: string;
  onQueryChange: (value: string) => void;
  onDuplicate: (session: SavedSession) => void;
  onEdit: (session: SavedSession) => void;
  onRemove: (id: string) => void;
  onCreate: () => void;
};

export default function SessionSidebar({
  sessions,
  activeId,
  openedCount,
  query,
  onQueryChange,
  onDuplicate,
  onEdit,
  onRemove,
  onCreate
}: Props) {
  const t = useT();
  return (
    // aside 保留 complementary 语义；面板底色/描边/圆角走 .sidebar（HeroUI token）
    <aside className="sidebar">
      <Header className="sidebar-head">
        <div>
          <span>{t("sidebar.title")}</span>
          <small>{sessions.length}</small>
        </div>
        <Hint label={t("sidebar.newSsh")}>
          <Button
            size="sm"
            isIconOnly
            aria-label={t("sidebar.newSsh")}
            onPress={onCreate}
          >
            <PlusOutlined />
          </Button>
        </Hint>
      </Header>
      <TextField
        className="search-box"
        aria-label={t(
          "sidebar.searchPlaceholder"
        )}
        value={query}
        onChange={onQueryChange}
      >
        <SearchOutlined />
        <Input
          placeholder={t(
            "sidebar.searchPlaceholder"
          )}
        />
      </TextField>
      <div className="group-title">
        <span>{t("sidebar.mine")}</span>
        <FolderOpenOutlined />
      </div>
      {sessions.length ? (
        <ListBox
          aria-label={t("sidebar.mine")}
          className="session-list"
          // 受控单选：高亮跟随 activeId（已打开标签），点击不改变选中
          selectionMode="single"
          selectedKeys={
            activeId ? [activeId] : []
          }
          onSelectionChange={() => {}}
        >
          {sessions.map(session => (
            <ListBox.Item
              key={session.id}
              id={session.id}
              // RAC 无障碍：复合内容项需提供纯文本值（type-to-select）
              textValue={session.name}
              className="session-item"
              onDoubleClick={() =>
                onDuplicate(session)
              }
            >
              <span className="session-icon">
                <LinkOutlined />
              </span>
              <span className="session-copy">
                <strong>{session.name}</strong>
                <small>
                  {session.kind === "local"
                    ? t("sidebar.localTerminal")
                    : `${session.username ? session.username + "@" : ""}${session.host}:${session.port}`}
                </small>
              </span>
              {session.id !== "local" && (
                <Button
                  className="edit"
                  variant="ghost"
                  size="sm"
                  isIconOnly
                  aria-label={t("sidebar.edit")}
                  onPress={() => onEdit(session)}
                >
                  <EditOutlined />
                </Button>
              )}
              {session.id !== "local" && (
                <Button
                  className="delete"
                  variant="ghost"
                  size="sm"
                  isIconOnly
                  aria-label={t("sidebar.remove")}
                  onPress={() =>
                    onRemove(session.id)
                  }
                >
                  <DeleteOutlined />
                </Button>
              )}
            </ListBox.Item>
          ))}
        </ListBox>
      ) : (
        <p className="empty-list">
          {t("sidebar.noMatch")}
        </p>
      )}
      <div className="sidebar-foot">
        <span className="status-dot"></span>
        <span>{t("sidebar.ready")}</span>
        <small>
          {t("sidebar.connections", {
            count: openedCount
          })}
        </small>
      </div>
    </aside>
  );
}
