// src/components/TerminalWorkspace.tsx
import {
  useCallback,
  useEffect,
  useRef,
  useState
} from "react";
import type { OpenSession } from "@/hooks/useTerminals";
import {
  Button,
  EmptyState,
  Input,
  Typography
} from "@heroui/react";
import Hint from "@/components/Hint";
import {
  PlusOutlined,
  DownOutlined,
  LinkOutlined
} from "@ant-design/icons";

type Props = {
  opened: OpenSession[];
  active?: OpenSession;
  disconnected: Record<string, boolean>;
  searchOpen: boolean;
  searchResult: { index: number; count: number };
  searchError: string;
  searchCaseSensitive: boolean;
  searchRegex: boolean;
  onActivate: (id: string) => void;
  onClose: (id: string) => void;
  onCreate: () => void;
  onSearch: (
    query: string,
    direction: "next" | "prev" | "input"
  ) => void;
  onCloseSearch: () => void;
  onToggleCaseSensitive: () => void;
  onToggleRegex: () => void;
  onTerminalHost: (
    el: HTMLElement | null
  ) => void;
};

export default function TerminalWorkspace({
  opened,
  active,
  disconnected,
  searchOpen,
  searchResult,
  searchError,
  searchCaseSensitive,
  searchRegex,
  onActivate,
  onClose,
  onCreate,
  onSearch,
  onCloseSearch,
  onToggleCaseSensitive,
  onToggleRegex,
  onTerminalHost
}: Props) {
  const [query, setQuery] = useState("");
  const searchInputRef =
    useRef<HTMLInputElement>(null);
  const tabsRef = useRef<HTMLDivElement>(null);
  const moreButtonRef =
    useRef<HTMLButtonElement>(null);
  const [dropdownOpen, setDropdownOpen] =
    useState(false);
  const [overflowed, setOverflowed] = useState<
    OpenSession[]
  >([]);
  const [moreListPos, setMoreListPos] = useState({
    top: 0,
    right: 0
  });

  const computeOverflow = useCallback(() => {
    const container = tabsRef.current;
    if (!container) return;
    const start = container.scrollLeft;
    const end = start + container.clientWidth;
    const hidden: OpenSession[] = [];
    container
      .querySelectorAll<HTMLElement>(".tab")
      .forEach((el, index) => {
        const left = el.offsetLeft;
        const right = left + el.offsetWidth;
        const session = opened[index];
        if (
          session &&
          (left < start || right > end)
        )
          hidden.push(session);
      });
    setOverflowed(hidden);
    if (!hidden.length) setDropdownOpen(false);
  }, [opened]);

  function positionMoreList() {
    if (!moreButtonRef.current) return;
    const rect =
      moreButtonRef.current.getBoundingClientRect();
    setMoreListPos({
      top: rect.bottom + 4,
      right: window.innerWidth - rect.right
    });
  }

  function toggleDropdown() {
    setDropdownOpen(prev => {
      const next = !prev;
      if (next) positionMoreList();
      return next;
    });
  }

  function activateOverflow(id: string) {
    const index = opened.findIndex(
      tab => tab.id === id
    );
    const tab =
      tabsRef.current?.querySelectorAll<HTMLElement>(
        ".tab"
      )[index];
    setDropdownOpen(false);
    onActivate(id);
    tab?.scrollIntoView({
      block: "nearest",
      inline: "nearest"
    });
  }

  function onTabsWheel(event: React.WheelEvent) {
    const container = tabsRef.current;
    if (!container) return;
    container.scrollLeft +=
      event.deltaY + event.deltaX;
  }

  function toggleAndSearch(toggle: () => void) {
    toggle();
    onSearch(query, "input");
  }

  // 搜索框打开时自动聚焦全选
  useEffect(() => {
    if (!searchOpen) return;
    requestAnimationFrame(() => {
      searchInputRef.current?.focus();
      searchInputRef.current?.select();
    });
  }, [searchOpen]);

  // 标签数变化时重算溢出
  useEffect(() => {
    requestAnimationFrame(computeOverflow);
  }, [opened.length, computeOverflow]);

  // 监听标签栏尺寸变化
  useEffect(() => {
    const container = tabsRef.current;
    if (!container) return;
    const ro = new ResizeObserver(() => {
      computeOverflow();
      if (dropdownOpen) positionMoreList();
    });
    ro.observe(container);
    return () => ro.disconnect();
  }, [dropdownOpen, opened, computeOverflow]);

  // 点击标签栏外部时收起下拉
  useEffect(() => {
    const onMousedown = (event: MouseEvent) => {
      const target = event.target as Node;
      const more =
        moreButtonRef.current?.parentElement;
      if (
        !tabsRef.current?.contains(target) &&
        !more?.contains(target)
      )
        setDropdownOpen(false);
    };
    document.addEventListener(
      "mousedown",
      onMousedown
    );
    return () =>
      document.removeEventListener(
        "mousedown",
        onMousedown
      );
  }, []);

  const searchCount = searchResult.count;
  const searchIndex = searchResult.index;

  return (
    <section className="terminal-pane">
      <div className="tabs-bar">
        <div
          ref={tabsRef}
          className="tabs"
          onScroll={computeOverflow}
          onWheel={onTabsWheel}
        >
          {opened.map(tab => (
            <Button
              key={tab.id}
              className={`tab${active?.id === tab.id ? " active" : ""}`}
              variant="tertiary"
              onPress={() => onActivate(tab.id)}
            >
              <span
                className={`status-dot${disconnected[tab.id] ? " off" : ""}`}
              ></span>
              <span>{tab.name}</span>
              {/* 关闭钮在 RAC Button 内部：pointerdown 也要拦截，
                  否则外层 Button 的 press 会先于 click 触发 */}
              <i
                onPointerDown={e =>
                  e.stopPropagation()
                }
                onClick={e => {
                  e.stopPropagation();
                  onClose(tab.id);
                }}
              >
                ×
              </i>
            </Button>
          ))}
          <Hint label="新建会话">
            <Button
              className="new-tab"
              variant="ghost"
              size="sm"
              isIconOnly
              aria-label="新建会话"
              onPress={onCreate}
            >
              <PlusOutlined />
            </Button>
          </Hint>
        </div>
        {overflowed.length > 0 && (
          <div className="tabs-more">
            <Hint
              label={`${overflowed.length} 个标签超出显示`}
            >
              <Button
                ref={moreButtonRef}
                className={`more-btn${dropdownOpen ? " open" : ""}`}
                variant="ghost"
                size="sm"
                isIconOnly
                aria-label="更多标签"
                onPress={toggleDropdown}
              >
                <DownOutlined />
              </Button>
            </Hint>
            {dropdownOpen && (
              <div
                className="more-list"
                style={{
                  top: `${moreListPos.top}px`,
                  right: `${moreListPos.right}px`
                }}
              >
                {overflowed.map(tab => (
                  <Button
                    key={tab.id}
                    className={`more-item${active?.id === tab.id ? " active" : ""}`}
                    variant="ghost"
                    size="sm"
                    onPress={() =>
                      activateOverflow(tab.id)
                    }
                  >
                    <span
                      className={`status-dot${disconnected[tab.id] ? " off" : ""}`}
                    ></span>
                    <span>{tab.name}</span>
                  </Button>
                ))}
              </div>
            )}
          </div>
        )}
      </div>

      {opened.length > 0 ? (
        // key 必须与空状态分支不同：终端元素是 replaceChildren 命令式挂进宿主的，
        // React 不感知；若两个分支复用同一 div 节点，关闭全部标签后残留的
        // .terminal-instance 会挤进 .empty-terminal 首位，把内容顶离垂直居中。
        <div
          key="host"
          ref={onTerminalHost}
          className="terminal-host"
        ></div>
      ) : (
        <EmptyState
          key="empty"
          className="empty-terminal"
        >
          <LinkOutlined />
          <Typography.Heading level={2}>
            选择一个会话开始连接
          </Typography.Heading>
          <Typography.Paragraph size="sm">
            从左侧打开本地终端，或新建一个 SSH
            会话。
          </Typography.Paragraph>
          <Button
            variant="primary"
            size="sm"
            onPress={onCreate}
          >
            <PlusOutlined />
            新建会话
          </Button>
        </EmptyState>
      )}

      <div className="terminal-status">
        <span>
          {active?.kind === "ssh"
            ? "SSH"
            : "LOCAL"}
        </span>
        <span>UTF-8</span>
        <span>
          {active?.terminal.cols || 0} ×{" "}
          {active?.terminal.rows || 0}
        </span>
      </div>

      {searchOpen && (
        <div className="find-box">
          <Input
            ref={searchInputRef}
            className="find-input"
            placeholder="查找"
            value={query}
            onChange={e => {
              setQuery(e.target.value);
              onSearch(e.target.value, "input");
            }}
            onKeyDown={e => {
              if (
                e.key === "Enter" &&
                !e.shiftKey
              ) {
                e.preventDefault();
                onSearch(query, "next");
              }
              if (
                e.key === "Enter" &&
                e.shiftKey
              ) {
                e.preventDefault();
                onSearch(query, "prev");
              }
              if (e.key === "Escape")
                onCloseSearch();
            }}
          />
          <span className="find-count">
            {searchError ||
              (searchCount
                ? `${searchIndex + 1}/${searchCount}`
                : query
                  ? "无匹配"
                  : "")}
          </span>
          <Hint label="上一个 (Shift+Enter)">
            <Button
              className="find-btn"
              variant="tertiary"
              size="sm"
              aria-label="上一个"
              onPress={() =>
                onSearch(query, "prev")
              }
            >
              ↑
            </Button>
          </Hint>
          <Hint label="下一个 (Enter)">
            <Button
              className="find-btn"
              variant="tertiary"
              size="sm"
              aria-label="下一个"
              onPress={() =>
                onSearch(query, "next")
              }
            >
              ↓
            </Button>
          </Hint>
          <Hint label="区分大小写">
            <Button
              className={`find-btn${searchCaseSensitive ? " on" : ""}`}
              variant="tertiary"
              size="sm"
              aria-label="区分大小写"
              onPress={() =>
                toggleAndSearch(
                  onToggleCaseSensitive
                )
              }
            >
              Aa
            </Button>
          </Hint>
          <Hint label="正则表达式">
            <Button
              className={`find-btn${searchRegex ? " on" : ""}`}
              variant="tertiary"
              size="sm"
              aria-label="正则表达式"
              onPress={() =>
                toggleAndSearch(onToggleRegex)
              }
            >
              .*
            </Button>
          </Hint>
          <Hint label="关闭 (Esc)">
            <Button
              className="find-btn"
              variant="tertiary"
              size="sm"
              aria-label="关闭查找"
              onPress={onCloseSearch}
            >
              ×
            </Button>
          </Hint>
        </div>
      )}
    </section>
  );
}

// src/components/TerminalWorkspace.vue
<script setup lang="ts">
import {
  ArrowDown,
  Connection,
  Plus
} from "@element-plus/icons-vue";
import type { OpenSession } from "@/composables/useTerminals";

const terminalHost = defineModel<
  HTMLElement | undefined
>("terminalHost");

const props = defineProps<{
  opened: OpenSession[];
  active?: OpenSession;
  searchOpen: boolean;
  searchResult: { index: number; count: number };
  searchError: string;
  searchCaseSensitive: boolean;
  searchRegex: boolean;
}>();
const emit = defineEmits<{
  activate: [id: string];
  close: [id: string];
  create: [];
  search: [
    query: string,
    direction: "next" | "prev" | "input"
  ];
  closeSearch: [];
  toggleCaseSensitive: [];
  toggleRegex: [];
}>();

// 搜索框：本地输入词 + 打开时自动聚焦全选
const query = ref("");
const searchInput = ref<HTMLInputElement>();

// 切换大小写/正则后立即用当前词重搜
function toggleAndSearch(toggle: () => void) {
  toggle();
  emit("search", query.value, "input");
}
const searchCount = computed(
  () => props.searchResult.count
);
const searchIndex = computed(
  () => props.searchResult.index
);

watch(
  () => props.searchOpen,
  open => {
    if (!open) return;
    nextTick(() => {
      searchInput.value?.focus();
      searchInput.value?.select();
    });
  }
);

// ---- 标签溢出处理 ----
// 标签超过标签栏宽度时，右侧出现"更多"下拉按钮，列出当前不可见的会话；
// 鼠标滚轮在标签栏上可横向滚动标签。
const tabsRef = ref<HTMLElement>();
const moreButtonRef = ref<HTMLButtonElement>();
const dropdownOpen = ref(false);
const overflowed = ref<OpenSession[]>([]);

/** 重新计算当前被挤出可视区域的标签（滚动位置变化时调用）。 */
function computeOverflow() {
  const container = tabsRef.value;
  if (!container) return;
  const start = container.scrollLeft;
  const end = start + container.clientWidth;
  const hidden: OpenSession[] = [];
  // .tab 顺序与 opened 一一对应（v-for 渲染），未完整落在可视区内即视为溢出。
  container
    .querySelectorAll<HTMLElement>(".tab")
    .forEach((el, index) => {
      const left = el.offsetLeft;
      const right = left + el.offsetWidth;
      const session = props.opened[index];
      if (
        session &&
        (left < start || right > end)
      )
        hidden.push(session);
    });
  overflowed.value = hidden;
  if (!hidden.length) dropdownOpen.value = false;
}

watch(
  () => props.opened.length,
  () => nextTick(computeOverflow),
  { flush: "post" }
);

/** 滚轮垂直滚动转为标签栏横向滚动。 */
function onTabsWheel(event: WheelEvent) {
  const container = tabsRef.value;
  if (!container) return;
  container.scrollLeft +=
    event.deltaY + event.deltaX;
}

// 下拉列表用 fixed 定位在按钮下方（tabs 容器的 overflow 会裁切 absolute 子元素）
const moreListPos = reactive({
  top: 0,
  right: 0
});

function toggleDropdown() {
  dropdownOpen.value = !dropdownOpen.value;
  if (dropdownOpen.value) positionMoreList();
}

function positionMoreList() {
  if (!moreButtonRef.value) return;
  const rect =
    moreButtonRef.value.getBoundingClientRect();
  moreListPos.top = rect.bottom + 4;
  moreListPos.right =
    window.innerWidth - rect.right;
}

/** 激活下拉列表中的会话，并将对应标签滚动到标签栏可视区。 */
function activateOverflow(id: string) {
  const index = props.opened.findIndex(
    tab => tab.id === id
  );
  const tab =
    tabsRef.value?.querySelectorAll<HTMLElement>(
      ".tab"
    )[index];
  dropdownOpen.value = false;
  emit("activate", id);
  tab?.scrollIntoView({
    block: "nearest",
    inline: "nearest"
  });
}

let resizeObserver: ResizeObserver | undefined;
let documentMousedown:
  ((e: MouseEvent) => void) | undefined;
let windowResize: (() => void) | undefined;

onMounted(() => {
  resizeObserver = new ResizeObserver(() => {
    computeOverflow();
    if (dropdownOpen.value) positionMoreList();
  });
  if (tabsRef.value)
    resizeObserver.observe(tabsRef.value);
  // 点击标签栏外部时收起下拉
  documentMousedown = (event: MouseEvent) => {
    const target = event.target as Node;
    const more =
      moreButtonRef.value?.parentElement;
    if (
      !tabsRef.value?.contains(target) &&
      !more?.contains(target)
    )
      dropdownOpen.value = false;
  };
  document.addEventListener(
    "mousedown",
    documentMousedown
  );
  windowResize = () => {
    if (dropdownOpen.value) positionMoreList();
  };
  window.addEventListener("resize", windowResize);
});

onBeforeUnmount(() => {
  resizeObserver?.disconnect();
  if (documentMousedown)
    document.removeEventListener(
      "mousedown",
      documentMousedown
    );
  if (windowResize)
    window.removeEventListener(
      "resize",
      windowResize
    );
});
</script>

<template>
  <section class="terminal-pane">
    <!-- 外层 relative 容器让更多按钮脱离滚动流，固定钉在标签栏可视区右侧 -->
    <div class="tabs-bar">
      <div
        ref="tabsRef"
        class="tabs"
        @scroll="computeOverflow"
        @wheel="onTabsWheel"
      >
        <button
          v-for="tab in opened"
          :key="tab.id"
          class="tab"
          :class="{
            active: active?.id === tab.id
          }"
          @click="$emit('activate', tab.id)"
        >
          <span class="status-dot"></span
          ><span>{{ tab.name }}</span
          ><i @click.stop="$emit('close', tab.id)"
            >×</i
          >
        </button>
        <button
          class="new-tab"
          title="新建会话"
          @click="$emit('create')"
        >
          <Plus />
        </button>
      </div>
      <div
        v-if="overflowed.length"
        class="tabs-more"
      >
        <button
          ref="moreButtonRef"
          class="more-btn"
          :class="{ open: dropdownOpen }"
          :title="`${overflowed.length} 个标签超出显示`"
          @click.stop="toggleDropdown"
        >
          <ArrowDown />
        </button>
        <div
          v-if="dropdownOpen"
          class="more-list"
          :style="{
            top: `${moreListPos.top}px`,
            right: `${moreListPos.right}px`
          }"
        >
          <button
            v-for="tab in overflowed"
            :key="tab.id"
            class="more-item"
            :class="{
              active: active?.id === tab.id
            }"
            @click="activateOverflow(tab.id)"
          >
            <span class="status-dot"></span
            ><span>{{ tab.name }}</span>
          </button>
        </div>
      </div>
    </div>
    <div
      v-if="opened.length"
      :ref="
        element =>
          (terminalHost = element as HTMLElement)
      "
      class="terminal-host"
    ></div>
    <div v-else class="empty-terminal">
      <Connection />
      <h2>选择一个会话开始连接</h2>
      <p>
        从左侧打开本地终端，或新建一个 SSH 会话。
      </p>
      <button @click="$emit('create')">
        <Plus />
        新建会话
      </button>
    </div>
    <div class="terminal-status">
      <span>{{
        active?.kind === "ssh" ? "SSH" : "LOCAL"
      }}</span
      ><span>UTF-8</span
      ><span
        >{{ active?.terminal.cols || 0 }} ×
        {{ active?.terminal.rows || 0 }}</span
      >
    </div>
    <!-- 查找框：右上角浮层，支持正则，Enter 下一个 / Shift+Enter 上一个 -->
    <div v-if="searchOpen" class="find-box">
      <input
        ref="searchInput"
        v-model="query"
        class="find-input"
        placeholder="查找"
        @input="emit('search', query, 'input')"
        @keydown.enter.prevent="
          emit('search', query, 'next')
        "
        @keydown.shift.enter.prevent="
          emit('search', query, 'prev')
        "
        @keydown.esc="emit('closeSearch')"
      />
      <span class="find-count">
        <template v-if="searchError">{{
          searchError
        }}</template>
        <template v-else-if="searchCount">{{
          `${searchIndex + 1}/${searchCount}`
        }}</template>
        <template v-else-if="query"
          >无匹配</template
        >
      </span>
      <button
        class="find-btn"
        title="上一个 (Shift+Enter)"
        @click="emit('search', query, 'prev')"
      >
        ↑
      </button>
      <button
        class="find-btn"
        title="下一个 (Enter)"
        @click="emit('search', query, 'next')"
      >
        ↓
      </button>
      <button
        class="find-btn"
        :class="{ on: searchCaseSensitive }"
        title="区分大小写"
        @click="
          toggleAndSearch(() =>
            emit('toggleCaseSensitive')
          )
        "
      >
        Aa
      </button>
      <button
        class="find-btn"
        :class="{ on: searchRegex }"
        title="正则表达式"
        @click="
          toggleAndSearch(() =>
            emit('toggleRegex')
          )
        "
      >
        .*
      </button>
      <button
        class="find-btn"
        title="关闭 (Esc)"
        @click="emit('closeSearch')"
      >
        ×
      </button>
    </div>
  </section>
</template>
