// src/features/terminal/TerminalWorkspace.tsx
import {
  useCallback,
  useEffect,
  useRef,
  useState
} from "react";
import type { OpenSession } from "@/features/terminal/useTerminals";
import {
  Button,
  Card,
  Dropdown,
  EmptyState,
  Input,
  Surface,
  Tabs,
  ToggleButton,
  Typography
} from "@heroui/react";
import Hint from "@/shared/components/Hint";
import {
  PlusOutlined,
  DownOutlined,
  DesktopOutlined,
  LinkOutlined
} from "@ant-design/icons";

type Props = {
  opened: OpenSession[];
  active?: OpenSession;
  disconnected: Record<string, boolean>;
  searchOpen: boolean;
  searchResult: { index: number; count: number };
  searchError: string;
  searchCaseSensitive: boolean;
  searchRegex: boolean;
  onActivate: (id: string) => void;
  onClose: (id: string) => void;
  onCreate: () => void;
  /** 打开本地终端：空状态里的次要操作。 */
  onOpenLocal: () => void;
  /** 点击标签后把键盘焦点交回对应终端。 */
  onFocusTerminal: (id: string) => void;
  onSearch: (
    query: string,
    direction: "next" | "prev" | "input"
  ) => void;
  onCloseSearch: () => void;
  onToggleCaseSensitive: () => void;
  onToggleRegex: () => void;
  onTerminalHost: (
    el: HTMLElement | null
  ) => void;
};

export default function TerminalWorkspace({
  opened,
  active,
  disconnected,
  searchOpen,
  searchResult,
  searchError,
  searchCaseSensitive,
  searchRegex,
  onActivate,
  onFocusTerminal,
  onClose,
  onCreate,
  onOpenLocal,
  onSearch,
  onCloseSearch,
  onToggleCaseSensitive,
  onToggleRegex,
  onTerminalHost
}: Props) {
  const [query, setQuery] = useState("");
  const searchInputRef =
    useRef<HTMLInputElement>(null);
  const tabsRef = useRef<HTMLDivElement>(null);
  const [overflowed, setOverflowed] = useState<
    OpenSession[]
  >([]);

  const computeOverflow = useCallback(() => {
    const container = tabsRef.current;
    if (!container) return;
    const start = container.scrollLeft;
    const end = start + container.clientWidth;
    const hidden: OpenSession[] = [];
    container
      .querySelectorAll<HTMLElement>(".tab")
      .forEach((el, index) => {
        const left = el.offsetLeft;
        const right = left + el.offsetWidth;
        const session = opened[index];
        if (
          session &&
          (left < start || right > end)
        )
          hidden.push(session);
      });
    setOverflowed(hidden);
  }, [opened]);

  function activateOverflow(id: string) {
    const index = opened.findIndex(
      tab => tab.id === id
    );
    const tab =
      tabsRef.current?.querySelectorAll<HTMLElement>(
        ".tab"
      )[index];
    onActivate(id);
    tab?.scrollIntoView({
      block: "nearest",
      inline: "nearest"
    });
    // 菜单关闭后 RAC 会把焦点还给触发器，等这一轮结束后再交给终端
    requestAnimationFrame(() =>
      onFocusTerminal(id)
    );
  }

  function onTabsWheel(event: React.WheelEvent) {
    const container = tabsRef.current;
    if (!container) return;
    container.scrollLeft +=
      event.deltaY + event.deltaX;
  }

  function toggleAndSearch(toggle: () => void) {
    toggle();
    onSearch(query, "input");
  }

  // 搜索框打开时自动聚焦全选
  useEffect(() => {
    if (!searchOpen) return;
    requestAnimationFrame(() => {
      searchInputRef.current?.focus();
      searchInputRef.current?.select();
    });
  }, [searchOpen]);

  // 标签数变化时重算溢出
  useEffect(() => {
    requestAnimationFrame(computeOverflow);
  }, [opened.length, computeOverflow]);

  // 监听标签栏尺寸变化：溢出集合随可视宽度变化重算
  useEffect(() => {
    const container = tabsRef.current;
    if (!container) return;
    const ro = new ResizeObserver(() => {
      computeOverflow();
    });
    ro.observe(container);
    return () => ro.disconnect();
  }, [opened, computeOverflow]);

  const searchCount = searchResult.count;
  const searchIndex = searchResult.index;

  return (
    // HeroUI Card 面板：圆角 + surface 底色，p-0/gap-0 抵消 Card 内边距
    <Card className="terminal-pane rounded-xl p-0 gap-0">
      <div className="tabs-bar">
        <div
          ref={tabsRef}
          className="tabs"
          onScroll={computeOverflow}
          onWheel={onTabsWheel}
        >
          {/* HeroUI Tabs：selectedKey 驱动激活态 + segment 滑动指示条；
              display:contents 让 Root 不参与 .tabs 的 flex 布局 */}
          <Tabs
            className="contents"
            selectedKey={active?.id}
            onSelectionChange={key => {
              if (key != null)
                onActivate(String(key));
            }}
          >
            <Tabs.List>
              {opened.map(tab => (
                <Tabs.Tab
                  key={tab.id}
                  id={tab.id}
                  className="tab"
                  // 点击已激活的标签不会触发 onSelectionChange（activeId 没变、
                  // 挂载用的 layout effect 也不会跑），这里统一在点击后交回焦点。
                  // RAC 在 press 阶段会聚焦 Tab 自身，故放到下一帧再抢，
                  // 保证最终的焦点落在终端上。关闭钮会 stopPropagation，点 × 不进这里。
                  onClick={() =>
                    requestAnimationFrame(() =>
                      onFocusTerminal(tab.id)
                    )
                  }
                >
                  <span
                    className={`status-dot${disconnected[tab.id] ? " off" : ""}`}
                  ></span>
                  <span>{tab.name}</span>
                  {/* 关闭钮在 RAC Tab 内部：pointerdown 也要拦截，
                      否则外层 Tab 的 press 会先于 click 触发 */}
                  <i
                    onPointerDown={e =>
                      e.stopPropagation()
                    }
                    onClick={e => {
                      e.stopPropagation();
                      onClose(tab.id);
                    }}
                  >
                    ×
                  </i>
                </Tabs.Tab>
              ))}
            </Tabs.List>
          </Tabs>
          <Hint label="新建会话">
            <Button
              className="new-tab"
              variant="ghost"
              size="sm"
              isIconOnly
              aria-label="新建会话"
              onPress={onCreate}
            >
              <PlusOutlined />
            </Button>
          </Hint>
        </div>
        {overflowed.length > 0 && (
          <div className="tabs-more">
            {/* 溢出标签菜单：原先是手写 fixed 定位 + 全局 mousedown 收起，
                现统一交给 HeroUI Dropdown（自动定位、焦点管理与关闭语义） */}
            <Dropdown.Root>
              {/* 触发器必须是 MenuTrigger 的直接子元素：外面包 Tooltip 的话
                  RAC 找不到 pressable child，菜单打不开并报 PressResponder 警告。
                  提示信息改用 aria-label 承载。 */}
              <Dropdown.Trigger
                className="more-btn"
                aria-label={`${overflowed.length} 个标签超出显示`}
              >
                <DownOutlined />
              </Dropdown.Trigger>
              <Dropdown.Popover placement="bottom end">
                <Dropdown.Menu
                  aria-label="更多标签"
                  selectionMode="single"
                  selectedKeys={
                    active ? [active.id] : []
                  }
                  onAction={key =>
                    activateOverflow(String(key))
                  }
                >
                  {overflowed.map(tab => (
                    <Dropdown.Item
                      key={tab.id}
                      id={tab.id}
                      textValue={tab.name}
                    >
                      <span
                        className={`status-dot${disconnected[tab.id] ? " off" : ""}`}
                      ></span>
                      <span className="more-item-name">
                        {tab.name}
                      </span>
                    </Dropdown.Item>
                  ))}
                </Dropdown.Menu>
              </Dropdown.Popover>
            </Dropdown.Root>
          </div>
        )}
      </div>

      {opened.length > 0 ? (
        // key 必须与空状态分支不同：终端元素是 replaceChildren 命令式挂进宿主的，
        // React 不感知；若两个分支复用同一 div 节点，关闭全部标签后残留的
        // .terminal-instance 会挤进 .empty-terminal 首位，把内容顶离垂直居中。
        <div
          key="host"
          ref={onTerminalHost}
          className="terminal-host"
        ></div>
      ) : (
        <EmptyState
          key="empty"
          className="empty-terminal"
        >
          {/* HeroUI Surface 做圆形图标底盘：空状态的视觉重心，
              比原先裸放的 42px 灰图标更有层次 */}
          <Surface className="empty-icon">
            <LinkOutlined />
          </Surface>
          <Typography.Heading
            level={3}
            className="empty-title"
          >
            选择一个会话开始连接
          </Typography.Heading>
          <Typography.Paragraph
            size="sm"
            className="empty-desc"
          >
            从左侧打开本地终端，或新建一个 SSH
            会话。
          </Typography.Paragraph>
          <div className="empty-actions">
            <Button
              variant="primary"
              size="sm"
              onPress={onCreate}
            >
              <PlusOutlined />
              新建会话
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onPress={onOpenLocal}
            >
              <DesktopOutlined />
              打开本地终端
            </Button>
          </div>
        </EmptyState>
      )}

      <div className="terminal-status">
        <span>
          {active?.kind === "ssh"
            ? "SSH"
            : "LOCAL"}
        </span>
        <span>UTF-8</span>
        <span>
          {active?.terminal.cols || 0} ×{" "}
          {active?.terminal.rows || 0}
        </span>
      </div>

      {searchOpen && (
        // HeroUI Surface：查找浮层的底色/描边/阴影跟随主题 token
        <Surface className="find-box">
          <Input
            ref={searchInputRef}
            className="find-input"
            placeholder="查找"
            value={query}
            onChange={e => {
              setQuery(e.target.value);
              onSearch(e.target.value, "input");
            }}
            onKeyDown={e => {
              if (
                e.key === "Enter" &&
                !e.shiftKey
              ) {
                e.preventDefault();
                onSearch(query, "next");
              }
              if (
                e.key === "Enter" &&
                e.shiftKey
              ) {
                e.preventDefault();
                onSearch(query, "prev");
              }
              if (e.key === "Escape")
                onCloseSearch();
            }}
          />
          <span className="find-count">
            {searchError ||
              (searchCount
                ? `${searchIndex + 1}/${searchCount}`
                : query
                  ? "无匹配"
                  : "")}
          </span>
          <Hint label="上一个 (Shift+Enter)">
            <Button
              className="find-btn"
              variant="tertiary"
              size="sm"
              aria-label="上一个"
              onPress={() =>
                onSearch(query, "prev")
              }
            >
              ↑
            </Button>
          </Hint>
          <Hint label="下一个 (Enter)">
            <Button
              className="find-btn"
              variant="tertiary"
              size="sm"
              aria-label="下一个"
              onPress={() =>
                onSearch(query, "next")
              }
            >
              ↓
            </Button>
          </Hint>
          <Hint label="区分大小写">
            <ToggleButton
              className="find-btn"
              variant="ghost"
              size="sm"
              aria-label="区分大小写"
              isSelected={searchCaseSensitive}
              onChange={() =>
                toggleAndSearch(
                  onToggleCaseSensitive
                )
              }
            >
              Aa
            </ToggleButton>
          </Hint>
          <Hint label="正则表达式">
            <ToggleButton
              className="find-btn"
              variant="ghost"
              size="sm"
              aria-label="正则表达式"
              isSelected={searchRegex}
              onChange={() =>
                toggleAndSearch(onToggleRegex)
              }
            >
              .*
            </ToggleButton>
          </Hint>
          <Hint label="关闭 (Esc)">
            <Button
              className="find-btn"
              variant="tertiary"
              size="sm"
              aria-label="关闭查找"
              onPress={onCloseSearch}
            >
              ×
            </Button>
          </Hint>
        </Surface>
      )}
    </Card>
  );
}

// src/components/TerminalWorkspace.vue
<script setup lang="ts">
import {
  ArrowDown,
  Connection,
  Plus
} from "@element-plus/icons-vue";
import type { OpenSession } from "@/composables/useTerminals";

const terminalHost = defineModel<
  HTMLElement | undefined
>("terminalHost");

const props = defineProps<{
  opened: OpenSession[];
  active?: OpenSession;
  searchOpen: boolean;
  searchResult: { index: number; count: number };
  searchError: string;
  searchCaseSensitive: boolean;
  searchRegex: boolean;
}>();
const emit = defineEmits<{
  activate: [id: string];
  close: [id: string];
  create: [];
  search: [
    query: string,
    direction: "next" | "prev" | "input"
  ];
  closeSearch: [];
  toggleCaseSensitive: [];
  toggleRegex: [];
}>();

// 搜索框：本地输入词 + 打开时自动聚焦全选
const query = ref("");
const searchInput = ref<HTMLInputElement>();

// 切换大小写/正则后立即用当前词重搜
function toggleAndSearch(toggle: () => void) {
  toggle();
  emit("search", query.value, "input");
}
const searchCount = computed(
  () => props.searchResult.count
);
const searchIndex = computed(
  () => props.searchResult.index
);

watch(
  () => props.searchOpen,
  open => {
    if (!open) return;
    nextTick(() => {
      searchInput.value?.focus();
      searchInput.value?.select();
    });
  }
);

// ---- 标签溢出处理 ----
// 标签超过标签栏宽度时，右侧出现"更多"下拉按钮，列出当前不可见的会话；
// 鼠标滚轮在标签栏上可横向滚动标签。
const tabsRef = ref<HTMLElement>();
const moreButtonRef = ref<HTMLButtonElement>();
const dropdownOpen = ref(false);
const overflowed = ref<OpenSession[]>([]);

/** 重新计算当前被挤出可视区域的标签（滚动位置变化时调用）。 */
function computeOverflow() {
  const container = tabsRef.value;
  if (!container) return;
  const start = container.scrollLeft;
  const end = start + container.clientWidth;
  const hidden: OpenSession[] = [];
  // .tab 顺序与 opened 一一对应（v-for 渲染），未完整落在可视区内即视为溢出。
  container
    .querySelectorAll<HTMLElement>(".tab")
    .forEach((el, index) => {
      const left = el.offsetLeft;
      const right = left + el.offsetWidth;
      const session = props.opened[index];
      if (
        session &&
        (left < start || right > end)
      )
        hidden.push(session);
    });
  overflowed.value = hidden;
  if (!hidden.length) dropdownOpen.value = false;
}

watch(
  () => props.opened.length,
  () => nextTick(computeOverflow),
  { flush: "post" }
);

/** 滚轮垂直滚动转为标签栏横向滚动。 */
function onTabsWheel(event: WheelEvent) {
  const container = tabsRef.value;
  if (!container) return;
  container.scrollLeft +=
    event.deltaY + event.deltaX;
}

// 下拉列表用 fixed 定位在按钮下方（tabs 容器的 overflow 会裁切 absolute 子元素）
const moreListPos = reactive({
  top: 0,
  right: 0
});

function toggleDropdown() {
  dropdownOpen.value = !dropdownOpen.value;
  if (dropdownOpen.value) positionMoreList();
}

function positionMoreList() {
  if (!moreButtonRef.value) return;
  const rect =
    moreButtonRef.value.getBoundingClientRect();
  moreListPos.top = rect.bottom + 4;
  moreListPos.right =
    window.innerWidth - rect.right;
}

/** 激活下拉列表中的会话，并将对应标签滚动到标签栏可视区。 */
function activateOverflow(id: string) {
  const index = props.opened.findIndex(
    tab => tab.id === id
  );
  const tab =
    tabsRef.value?.querySelectorAll<HTMLElement>(
      ".tab"
    )[index];
  dropdownOpen.value = false;
  emit("activate", id);
  tab?.scrollIntoView({
    block: "nearest",
    inline: "nearest"
  });
}

let resizeObserver: ResizeObserver | undefined;
let documentMousedown:
  ((e: MouseEvent) => void) | undefined;
let windowResize: (() => void) | undefined;

onMounted(() => {
  resizeObserver = new ResizeObserver(() => {
    computeOverflow();
    if (dropdownOpen.value) positionMoreList();
  });
  if (tabsRef.value)
    resizeObserver.observe(tabsRef.value);
  // 点击标签栏外部时收起下拉
  documentMousedown = (event: MouseEvent) => {
    const target = event.target as Node;
    const more =
      moreButtonRef.value?.parentElement;
    if (
      !tabsRef.value?.contains(target) &&
      !more?.contains(target)
    )
      dropdownOpen.value = false;
  };
  document.addEventListener(
    "mousedown",
    documentMousedown
  );
  windowResize = () => {
    if (dropdownOpen.value) positionMoreList();
  };
  window.addEventListener("resize", windowResize);
});

onBeforeUnmount(() => {
  resizeObserver?.disconnect();
  if (documentMousedown)
    document.removeEventListener(
      "mousedown",
      documentMousedown
    );
  if (windowResize)
    window.removeEventListener(
      "resize",
      windowResize
    );
});
</script>

<template>
  <section class="terminal-pane">
    <!-- 外层 relative 容器让更多按钮脱离滚动流，固定钉在标签栏可视区右侧 -->
    <div class="tabs-bar">
      <div
        ref="tabsRef"
        class="tabs"
        @scroll="computeOverflow"
        @wheel="onTabsWheel"
      >
        <button
          v-for="tab in opened"
          :key="tab.id"
          class="tab"
          :class="{
            active: active?.id === tab.id
          }"
          @click="$emit('activate', tab.id)"
        >
          <span class="status-dot"></span
          ><span>{{ tab.name }}</span
          ><i @click.stop="$emit('close', tab.id)"
            >×</i
          >
        </button>
        <button
          class="new-tab"
          title="新建会话"
          @click="$emit('create')"
        >
          <Plus />
        </button>
      </div>
      <div
        v-if="overflowed.length"
        class="tabs-more"
      >
        <button
          ref="moreButtonRef"
          class="more-btn"
          :class="{ open: dropdownOpen }"
          :title="`${overflowed.length} 个标签超出显示`"
          @click.stop="toggleDropdown"
        >
          <ArrowDown />
        </button>
        <div
          v-if="dropdownOpen"
          class="more-list"
          :style="{
            top: `${moreListPos.top}px`,
            right: `${moreListPos.right}px`
          }"
        >
          <button
            v-for="tab in overflowed"
            :key="tab.id"
            class="more-item"
            :class="{
              active: active?.id === tab.id
            }"
            @click="activateOverflow(tab.id)"
          >
            <span class="status-dot"></span
            ><span>{{ tab.name }}</span>
          </button>
        </div>
      </div>
    </div>
    <div
      v-if="opened.length"
      :ref="
        element =>
          (terminalHost = element as HTMLElement)
      "
      class="terminal-host"
    ></div>
    <div v-else class="empty-terminal">
      <Connection />
      <h2>选择一个会话开始连接</h2>
      <p>
        从左侧打开本地终端，或新建一个 SSH 会话。
      </p>
      <button @click="$emit('create')">
        <Plus />
        新建会话
      </button>
    </div>
    <div class="terminal-status">
      <span>{{
        active?.kind === "ssh" ? "SSH" : "LOCAL"
      }}</span
      ><span>UTF-8</span
      ><span
        >{{ active?.terminal.cols || 0 }} ×
        {{ active?.terminal.rows || 0 }}</span
      >
    </div>
    <!-- 查找框：右上角浮层，支持正则，Enter 下一个 / Shift+Enter 上一个 -->
    <div v-if="searchOpen" class="find-box">
      <input
        ref="searchInput"
        v-model="query"
        class="find-input"
        placeholder="查找"
        @input="emit('search', query, 'input')"
        @keydown.enter.prevent="
          emit('search', query, 'next')
        "
        @keydown.shift.enter.prevent="
          emit('search', query, 'prev')
        "
        @keydown.esc="emit('closeSearch')"
      />
      <span class="find-count">
        <template v-if="searchError">{{
          searchError
        }}</template>
        <template v-else-if="searchCount">{{
          `${searchIndex + 1}/${searchCount}`
        }}</template>
        <template v-else-if="query"
          >无匹配</template
        >
      </span>
      <button
        class="find-btn"
        title="上一个 (Shift+Enter)"
        @click="emit('search', query, 'prev')"
      >
        ↑
      </button>
      <button
        class="find-btn"
        title="下一个 (Enter)"
        @click="emit('search', query, 'next')"
      >
        ↓
      </button>
      <button
        class="find-btn"
        :class="{ on: searchCaseSensitive }"
        title="区分大小写"
        @click="
          toggleAndSearch(() =>
            emit('toggleCaseSensitive')
          )
        "
      >
        Aa
      </button>
      <button
        class="find-btn"
        :class="{ on: searchRegex }"
        title="正则表达式"
        @click="
          toggleAndSearch(() =>
            emit('toggleRegex')
          )
        "
      >
        .*
      </button>
      <button
        class="find-btn"
        title="关闭 (Esc)"
        @click="emit('closeSearch')"
      >
        ×
      </button>
    </div>
  </section>
</template>
