// src/App.tsx
import {
  useEffect,
  useRef,
  useState
} from "react";
import { Alert } from "@heroui/react";
import { useSessions } from "@/hooks/useSessions";
import { useTerminals } from "@/hooks/useTerminals";
import type { SavedSession } from "@/domain/session";
import AppHeader from "@/components/AppHeader";
import SessionSidebar from "@/components/SessionSidebar";
import TerminalWorkspace from "@/components/TerminalWorkspace";
import SessionDialog from "@/components/SessionDialog";
import PasswordDialog from "@/components/PasswordDialog";
import AppLoading, {
  type AppLoadingHandle
} from "@/components/AppLoading";
import "@xterm/xterm/css/xterm.css";
import "@/styles/app.scss";
import "@/styles/main.css";

export default function App() {
  const [dialogOpen, setDialogOpen] =
    useState(false);
  const [error, setError] = useState("");
  const [editingSession, setEditingSession] =
    useState<SavedSession | null>(null);
  const [appReady, setAppReady] = useState(false);
  const appLoadingRef =
    useRef<AppLoadingHandle>(null);

  const {
    sessions,
    query,
    setQuery,
    filteredSessions,
    save,
    update,
    remove
  } = useSessions();

  const terminals = useTerminals(
    reason => setError(String(reason)),
    (sourceSessionId, encrypted) => {
      const session = sessions.find(
        item => item.id === sourceSessionId
      );
      if (session)
        update({
          ...session,
          password: encrypted
        });
    }
  );

  function openCreate() {
    setEditingSession(null);
    setDialogOpen(true);
  }

  function openEdit(session: SavedSession) {
    setEditingSession(session);
    setDialogOpen(true);
  }

  function saveSession(session: SavedSession) {
    if (editingSession) update(session);
    else save(session);
    setDialogOpen(false);
  }

  const loadingTimerRef =
    useRef<ReturnType<typeof setTimeout>>(
      undefined
    );

  useEffect(() => {
    const first = sessions[0];
    if (first) terminals.open(first);
    // 动效至少播放 5 秒：主界面渲染就绪后等待剩余时间，再淡出进入应用。
    loadingTimerRef.current = setTimeout(() => {
      appLoadingRef.current?.finish();
    }, 5000);
    return () =>
      clearTimeout(loadingTimerRef.current);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function handleLoadingFinished() {
    clearTimeout(loadingTimerRef.current);
    setAppReady(true);
  }

  return (
    <main className="shell-app">
      <AppHeader />
      <section className="workspace">
        <SessionSidebar
          sessions={filteredSessions}
          activeId={
            terminals.active?.sourceSessionId ??
            ""
          }
          openedCount={terminals.opened.length}
          query={query}
          onQueryChange={setQuery}
          onDuplicate={terminals.duplicate}
          onEdit={openEdit}
          onRemove={remove}
          onCreate={openCreate}
        />
        <TerminalWorkspace
          opened={terminals.opened}
          active={terminals.active}
          disconnected={terminals.disconnected}
          searchOpen={terminals.searchOpen}
          searchResult={terminals.searchResult}
          searchError={terminals.searchError}
          searchCaseSensitive={
            terminals.searchCaseSensitive
          }
          searchRegex={terminals.searchRegex}
          onActivate={terminals.activate}
          onClose={terminals.close}
          onCreate={openCreate}
          onSearch={terminals.search}
          onCloseSearch={terminals.closeSearch}
          onToggleCaseSensitive={
            terminals.toggleCaseSensitive
          }
          onToggleRegex={terminals.toggleRegex}
          onTerminalHost={
            terminals.setTerminalHost
          }
        />
      </section>
      <SessionDialog
        key={editingSession?.id ?? "new"}
        open={dialogOpen}
        session={editingSession}
        onClose={() => setDialogOpen(false)}
        onSave={saveSession}
      />
      {terminals.passwordRequest && (
        <PasswordDialog
          key={
            terminals.passwordRequest.session.id
          }
          session={
            terminals.passwordRequest.session
          }
          onSubmit={terminals.submitPassword}
          onCancel={terminals.cancelPassword}
        />
      )}
      {error && (
        <Alert
          status="danger"
          className="toast"
          onClick={() => setError("")}
        >
          <Alert.Content>
            <Alert.Description>
              {error}
            </Alert.Description>
          </Alert.Content>
        </Alert>
      )}
      {!appReady && (
        <AppLoading
          ref={appLoadingRef}
          onFinished={handleLoadingFinished}
        />
      )}
    </main>
  );
}

// src/App.vue
<script setup lang="ts">
import TerminalWorkspace from "@/components/TerminalWorkspace.vue";
import PasswordDialog from "@/components/PasswordDialog.vue";
import AppLoading from "@/components/AppLoading.vue";
import { useSessions } from "@/composables/useSessions";
import { useTerminals } from "@/composables/useTerminals";
import type { SavedSession } from "@/domain/session";
import "@xterm/xterm/css/xterm.css";
import "@/styles/app.scss";

const dialogOpen = ref(false);
const error = ref("");
const editingSession = ref<SavedSession | null>(
  null
);
const appReady = ref(false);
const appLoading = ref<InstanceType<
  typeof AppLoading
> | null>(null);
const {
  sessions,
  query,
  filteredSessions,
  save,
  update,
  remove
} = useSessions();
const terminals = useTerminals(
  reason => (error.value = String(reason)),
  // 首次连接输入的密码加密后写回对应会话，下次双击直接解密连接。
  (sourceSessionId, encrypted) => {
    const session = sessions.value.find(
      item => item.id === sourceSessionId
    );
    if (session)
      update({ ...session, password: encrypted });
  }
);

function openCreate() {
  editingSession.value = null;
  dialogOpen.value = true;
}

function openEdit(session: SavedSession) {
  editingSession.value = session;
  dialogOpen.value = true;
}

function saveSession(session: SavedSession) {
  if (editingSession.value) update(session);
  else save(session);
  dialogOpen.value = false;
}

onMounted(async () => {
  const first = sessions.value[0];
  if (first) terminals.open(first);
  // 动效至少播放 2 秒：主界面渲染就绪后等待剩余时间，再淡出进入应用。
  await Promise.all([
    nextTick(),
    new Promise(resolve =>
      setTimeout(resolve, 5000)
    )
  ]);
  appLoading.value?.finish();
});

function loadingFinished() {
  appReady.value = true;
}
</script>

<template>
  <main class="shell-app">
    <AppHeader />
    <section class="workspace">
      <SessionSidebar
        v-model:query="query"
        :sessions="filteredSessions"
        :active-id="
          terminals.active.value
            ?.sourceSessionId ?? ''
        "
        :opened-count="terminals.opened.length"
        @duplicate="terminals.duplicate"
        @edit="openEdit"
        @remove="remove"
        @create="openCreate"
      />
      <TerminalWorkspace
        v-model:terminal-host="
          terminals.terminalHost.value
        "
        :opened="terminals.opened"
        :active="terminals.active.value"
        :search-open="terminals.searchOpen.value"
        :search-result="
          terminals.searchResult.value
        "
        :search-error="
          terminals.searchError.value
        "
        :search-case-sensitive="
          terminals.searchCaseSensitive.value
        "
        :search-regex="
          terminals.searchRegex.value
        "
        @activate="terminals.activate"
        @close="terminals.close"
        @create="openCreate"
        @search="terminals.search"
        @close-search="terminals.closeSearch"
        @toggle-case-sensitive="
          terminals.toggleCaseSensitive
        "
        @toggle-regex="terminals.toggleRegex"
      />
    </section>
    <SessionDialog
      :open="dialogOpen"
      :session="editingSession"
      @close="dialogOpen = false"
      @save="saveSession"
    />
    <PasswordDialog
      v-if="terminals.passwordRequest.value"
      :session="
        terminals.passwordRequest.value.session
      "
      @submit="terminals.submitPassword"
      @cancel="terminals.cancelPassword"
    />
    <div
      v-if="error"
      class="toast"
      @click="error = ''"
    >
      {{ error }}
    </div>
    <AppLoading
      v-if="!appReady"
      ref="appLoading"
      @finished="loadingFinished"
    />
  </main>
</template>
